[[language]]
name = "json"
auto-format = true

[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "sql"
auto-format = true

[[language]]
name = "rust"
auto-format = true

# TODO(nick): make this work outside of macOS.
[language-server.rust-analyzer]
command = "/opt/homebrew/bin/rust-analyzer"

[language-server.rust-analyzer.config.checkOnSave]
command = "check" # clippy works too
extraArgs = ["--target-dir", "target/rust-analyzer"]

[language-server.rust-analyzer.config.cargo]
allFeatures = true

[language-server.rust-analyzer.config.check]
command = "check" # clippy works too
