default:
    @just --list

run distribution="nixos":
    @./scripts/run.sh {{distribution}}

shell distribution="nixos":
    @./scripts/shell.sh {{distribution}}

stop distribution="nixos":
    @./scripts/stop.sh {{distribution}}
